// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDugK6p-PgzGi1_Qp9x_DhMKQeEXOfVI',
    appId: '1:144898093051:web:89dd75d3229f4f1192e55e',
    messagingSenderId: '144898093051',
    projectId: 'athanttestt',
    authDomain: 'athanttestt.firebaseapp.com',
    storageBucket: 'athanttestt.appspot.com',
    measurementId: 'G-T5RN8M90CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLefscQl729Jd_9EQYtcjXL-ATJ5aqi-I',
    appId: '1:144898093051:android:1c7f79dd7dd9ec7192e55e',
    messagingSenderId: '144898093051',
    projectId: 'athanttestt',
    storageBucket: 'athanttestt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMLQVvte5XaaEeiFUbMZIw2WDfzo2DR0',
    appId: '1:144898093051:ios:eca7952408c5883992e55e',
    messagingSenderId: '144898093051',
    projectId: 'athanttestt',
    storageBucket: 'athanttestt.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtMLQVvte5XaaEeiFUbMZIw2WDfzo2DR0',
    appId: '1:144898093051:ios:eca7952408c5883992e55e',
    messagingSenderId: '144898093051',
    projectId: 'athanttestt',
    storageBucket: 'athanttestt.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHDugK6p-PgzGi1_Qp9x_DhMKQeEXOfVI',
    appId: '1:144898093051:web:9aad634eb7a15f1792e55e',
    messagingSenderId: '144898093051',
    projectId: 'athanttestt',
    authDomain: 'athanttestt.firebaseapp.com',
    storageBucket: 'athanttestt.appspot.com',
    measurementId: 'G-36R6KP9LLY',
  );
}
